export let SEARCHING_BOOKS = 'SEARCHING_BOOKS'
export let ADD_BOOKS = 'ADD_BOOKS'
export let ALL_BOOKS_NUMBER = 'ALL_BOOKS_NUMBER'
export let IS_LOADING_ALL_BOOKS = 'IS_LOADING_ALL_BOOKS'


export let IS_LOADING = 'IS_LOADING'